# // It is weird when having 2 files for environment variables
# // 1. configuration.yaml : This file used to alter runtime behaviors after it is compiled.
# // 2. .env : This file used only for build + test in development environment.
# // Another reason when using DATABASE_URL here is that sqlx reaches to Postgres at compile time and relies on this variable
# // So we need to set it to .env for Sqlx
application:
  port: 8000

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "123456"
  database_name: "newsletter"